basePath: /
host: localhost:8000
info:
  contact:
    email: support@swagger.io
    name: Renata Borges
    url: http://www.linkedin.com/renataborgestech
  description: Product API with authentication
  license:
    name: Full Cycle License
    url: http://www.fullcycle.com.br
  termsOfService: http://swagger.io/terms/
  title: Go Expert API Example
  version: "1.0"
paths: {}
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
